import styles from "../components/Signupform.module.css";
import Head from 'next/head'
import Lower from "../components/Lower";
import React, {useState } from 'react'
import Axios from 'axios' 
import {useRouter} from 'next/router';

export default function App() {
    const router = useRouter()
    const get_email = router.query.email
    const [changePass, setPass] = useState('')
    const [changeRepass, setRepass] = useState('')
    const [changeStatuseErr, changeRegstaterr] = useState('')
    
    const change = () =>{
        Axios.post('http://localhost:2023/change',{
          email: get_email,
          password: changePass,
          repass: changeRepass
        }).then((response)=>{
          console.log(response)
          if (response.data.message == "Successfully Reset Password"){
            
            Swal.fire({
              icon: 'success',
              title: 'Successfully Reset Password!',
              confirmButtonColor: '#3085d6',
              confirmButtonText: 'Okay'
              }).then((result) => {
              if (result.isConfirmed) {
                  window.location.href='/Signin';
                  console.log(response);
                }
              })
            
          }else{
            changeRegstaterr(response.data.message)
          }
          
        })
    
    
      };
  
   
  return (
    <>
    <Head>
        <title>Reset Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      </Head>
    <div className={styles.container}>

        <div className="container py-8 h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col-12 col-md-12 col-lg-12 col-xl-7">
              <div className="card bg-gradient bg-primary text-white">
                <div className="card-body p-5 ">

                  <div className="mb-md-5 mt-md-4 pb-5">

                    <div className="text-center">
                      <h2 className="fw-bold mb-2 text-uppercase">Reset Password</h2>
                      <p className="text-white-50 mb-5">Create new password</p>
                    </div>
                    
                    <h3 className='text-warning text-center'>{changeStatuseErr}</h3>
                    <div className="form-outline form-white mb-4">
                        <label htmlFor="oldpin">Password:  </label><br></br>
                        <input type="password" onChange={(e) => { setPass(e.target.value); }} id="typePasswordX" className="form-control form-control-lg" placeholder='Enter Password' required />
                    </div>
                    <div className="form-outline form-white mb-4">
                        <label htmlFor="oldpin">Retype Password:  </label><br></br>
                        <input type="password" onChange={(e) => { setRepass(e.target.value); }} id="typePasswordreX" className="form-control form-control-lg" placeholder='Retype Password' required />
                    </div>

                    
                    <div className="row d-flex justify-content-center align-items-center h-100 p-3">
                        <button className="btn btn-outline-light btn-lg px-5" onClick={change} type="submit">Reset Password</button>
                    </div>
                    
                    
                    <div className="text-center pt-5">
                    <p className="mb-0"><a href="./" className="text-white-50 fw-bold">Back</a>
                      </p>
                    </div>
                  </div>

                  

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <Lower/>
    </>
  );
}


