import styles from "../components/Welcome.module.css";
import Head from 'next/head'
// import Lower from "../components/Lower";

// import { useEffect, useState } from "react";


export const getStaticProps = async () => {
    const res = await fetch('http://localhost:3001/data');
    const data = await res.json();
  
   
    return{
      props: { image_blob : data }
    }
  }
  
const getdata = ({ image_blob }) => {
    return (
    <>
    <Head>
        <title>Motion Detection Record</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      </Head>
    <div className={styles.container}>

        <div className="container py-8 h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col-12 col-md-12 col-lg-12 col-xl-7">
                <div className="text-center">
                    <h2 className="fw-bold text-white mb-2 text-uppercase">Motion Detection Record</h2>
                    <p className="text-white-50 mb-5">Viewing of captured images using pandas & opencv library.</p>
                </div>

                <div className="row d-flex justify-content-center align-items-center h-100">
                    {image_blob.map(datas => (
                        

                        <table className="table table-striped table-dark">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Starting Time</th>
                                    <th>Ending Time</th>
                                    <th>Image</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr className="table-active">
                                    <th>{datas.id} </th>
                                    <td>{datas.start} </td>
                                    <td>{datas.end} </td>
                                    <td><img src={`data:image/png;base64,${datas.image}`} alt="" width="380" height="300" /></td>
                                </tr>

                            </tbody>
                        </table>   

                    ))}

                </div>  
            </div>
          </div>
        </div>
      </div>
      <br/><br/><br/><br/><br/>
    </>

    )

}
export const config = {
    api: {
        bodyParser: {
            sizeLimit: '4mb',
        },
    },
}
export default getdata;