import styles from "../components/Signupform.module.css";
import Head from 'next/head'
import Lower from "../components/Lower";
import React, {useState } from 'react'
import Axios from 'axios' 

export default function App() {
  const [logUser, setUser] = useState('')
    const [logPass, setPass] = useState('')
    const [logStatuseErr, setLogstaterr] = useState('')
    const login = () =>{
        Axios.post('http://localhost:2023/read',{
          username: logUser, 
          password: logPass
        }).then((response) => {
          if (response.data.message == 'Verified'){
            Swal.fire({
              icon: 'success',
              title: 'Verified!',
              confirmButtonColor: '#3085d6',
              confirmButtonText: 'Okay'
              }).then((result) => {
              if (result.isConfirmed) {
                  window.location.href='/Dashboard';
                  console.log(response);
                }
              })
            
          }else{
            setLogstaterr(response.data.message)
          }
        });

    };
    const [findEmail, setFindemail] = useState('')
    const [findStatuseErr, findstaterr] = useState('')
    const forgot = () =>{
      Axios.post('http://localhost:2023/find',{
        email: findEmail, 
      }).then((response) => {
        if (response.data.message == 'Email found'){
          window.location.href='/changepass?email='+findEmail
        }else{
          findstaterr(response.data.message)
        }
      });

  };
  
   
  return (
    <>
    <Head>
        <title>Log-in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      </Head>
    
        {/* <div className="container py-5 h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col-12 col-md-8 col-lg-6 col-xl-5">
              <div className="card bg-dark text-white">
                <div className="card-body p-5 text-center">

                  <div className="mb-md-5 mt-md-4 pb-5">

                    <h2 className="fw-bold mb-2 text-uppercase">Login</h2>
                    <p className="text-white-50 mb-5">Please enter your username and password   </p>


                    <h3 className='text-danger'>{logStatuseErr}</h3>
                    <div className="form-outline form-white mb-4">
                      <input type="text" id="typeUsernameX" onChange={(e) => { setUser(e.target.value); }} className="form-control form-control-lg" placeholder='Enter Username' required />
                    </div>

                    <div className="form-outline form-white mb-4">
                      <input type="password" id="typePasswordX" onChange={(e) => { setPass(e.target.value); }} className="form-control form-control-lg" placeholder='Enter Password' required />
                    </div>

                    <p className="small mb-5 pb-lg-2"><a className="text-white-50" data-bs-toggle="modal" data-bs-target="#forgotpass" href="">Forgot password?</a></p>

                    <button className="btn btn-outline-light btn-lg px-5" onClick={login} type="submit">Login</button>


                  </div>

                  <div>
                    <p className="mb-0">Don't have an account? <a href="signup" className="text-white-50 fw-bold">Sign Up</a>
                    </p>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div> */}



      <div className={styles.container}>

        <div className="container py-8 h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col-12 col-md-12 col-lg-12 col-xl-7">
              <div className="card bg-gradient bg-primary text-white">
                <div className="card-body p-5 ">

                  <div className="mb-md-5 mt-md-4 pb-5">

                    <div className="text-center">
                      <h2 className="fw-bold mb-2 text-uppercase">Login</h2>
                      <p className="text-white-50 mb-5">Please enter your username and password   </p>
                    </div>



                    <h3 className='text-warning text-center'>{logStatuseErr}</h3>
                    <div className="form-outline form-white mb-4">
                      <label htmlFor="oldpin">Username:  </label><br></br>
                      <input type="text" id="typeUsernameX" onChange={(e) => { setUser(e.target.value); }} className="form-control form-control-lg" placeholder='Enter Username' required />
                    </div>

                    <div className="form-outline form-white mb-4">
                      <label htmlFor="oldpin">Password:  </label><br></br>
                      <input type="password" id="typePasswordX" onChange={(e) => { setPass(e.target.value); }} className="form-control form-control-lg" placeholder='Enter Password' required />
                    </div>

                    <p className="small mb-3 text-center pb-lg-2"><a className="text-white-50" data-bs-toggle="modal" data-bs-target="#forgotpass" href="">Forgot password?</a></p>



                    <div className="row d-flex align-items-center p-3">
                      <button className="btn btn-outline-light btn-lg px-5" onClick={login} type="submit">Login</button>
                    </div>

                    <div className="text-center pt-5">
                      <p className="mb-0">Don't have an account? <a href="/Signup" className="text-white-50 fw-bold">Sign-up</a>
                      </p>
                    </div>
                  </div>



                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    

    <div className="modal fade" id="forgotpass" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title text-dark " id="exampleModalLabel">Forgot Password</h5>
                <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
                <div className="modal-body">
                  <h3 className='text-warning text-center'>{findStatuseErr}</h3>
                  <input type="email" id="typeEmailX" className="form-control form-control-lg" onChange={(e)=>{setFindemail(e.target.value);}} placeholder='Enter Email' required />
                
                </div>
                <div className="modal-footer">
                  <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="submit" className="btn btn-danger" onClick={forgot}>Submit</button>
                </div>


            </div>
          </div>
        </div>
    <Lower/>
    </>
  );
}


